# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Debug'

steps:
- script: |
   echo '##vso[task.setvariable variable=path]$(PATH):/c/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/bin'
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: FortifyOnDemandStatic@8
  inputs:
    FortifyProjects: '$(Build.SourcesDirectory)'
    FodConnection: 'FOD_Local_Connection'
    ReleaseOptions: '0'
    ReleaseId: 277
    EntitlementSelection: '1'
    EntitlementPreference: '1'
    OverrideScanSettings: '2'
    InProgressScanActionType: '2'
    RemediationScanPreference: '0'
    BuildType: 'msbuild'
    BuildFile: 'eShopOnWeb.sln'
    PolicyFailAction: '0'
